// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanSu.Data;

#nullable disable

namespace QuanLyNhanSu.Migrations
{
    [DbContext(typeof(QLNhanSuDbContext))]
    [Migration("20260324010412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhanSu.Data.BaoHiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiBaoHiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("BaoHiem");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.HasKey("MaHD");

                    b.HasIndex("HeSoLuong");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaPB");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Luong", b =>
                {
                    b.Property<int>("HeSoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeSoLuong"));

                    b.Property<int>("LuongCB")
                        .HasColumnType("int");

                    b.HasKey("HeSoLuong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoCM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TTHonNhan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrinhDoHV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("HeSoLuong");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaPB");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhongBan", b =>
                {
                    b.Property<string>("MaPB")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPB");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhuCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<string>("LoaiPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("Tien")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Taikhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Taikhoan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ThuongPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date");

                    b.Property<int?>("Tien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ThuongPhat");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ctChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.BaoHiem", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("BaoHiem")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChamCong", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.Luong", "Luong")
                        .WithMany("HopDong")
                        .HasForeignKey("HeSoLuong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.ChucVu", "ChucVu")
                        .WithMany("HopDong")
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.PhongBan", "PhongBan")
                        .WithMany("HopDong")
                        .HasForeignKey("MaPB")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("Luong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.Luong", "Luong")
                        .WithMany("NhanVien")
                        .HasForeignKey("HeSoLuong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.HopDong", "HopDong")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaPB")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Luong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhuCap", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("PhuCap")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Taikhoan", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("Taikhoan")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ThuongPhat", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ThuongPhat")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ctChucVu", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.ChucVu", "ChucVu")
                        .WithMany("ctChucVu")
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ctChucVu")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChucVu", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Luong", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.Navigation("BaoHiem");

                    b.Navigation("ChamCong");

                    b.Navigation("PhuCap");

                    b.Navigation("Taikhoan");

                    b.Navigation("ThuongPhat");

                    b.Navigation("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhongBan", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
