// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanSu.Data;

#nullable disable

namespace QuanLyNhanSu.Migrations
{
    [DbContext(typeof(QLNhanSuDbContext))]
    [Migration("20260129115912_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhanSu.Data.BaoHiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("BaoHiem");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChamCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVuMaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<int>("LuongHeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongBanMaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHD");

                    b.HasIndex("ChucVuMaCV");

                    b.HasIndex("LuongHeSoLuong");

                    b.HasIndex("PhongBanMaPB");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Luong", b =>
                {
                    b.Property<int>("HeSoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeSoLuong"));

                    b.Property<int>("LuongCB")
                        .HasColumnType("int");

                    b.HasKey("HeSoLuong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HopDongMaHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LuongHeSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongBanMaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoCM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TTHonNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("HopDongMaHD");

                    b.HasIndex("LuongHeSoLuong");

                    b.HasIndex("PhongBanMaPB");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhongBan", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPB");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhuCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Tien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Taikhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("Taikhoan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ThuongPhat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Tien")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("ThuongPhat");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ctChucVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChucVuMaCV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ChucVuMaCV");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.BaoHiem", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("BaoHiem")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChamCong", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.ChucVu", "ChucVu")
                        .WithMany("HopDong")
                        .HasForeignKey("ChucVuMaCV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.Luong", "Luong")
                        .WithMany("HopDong")
                        .HasForeignKey("LuongHeSoLuong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.PhongBan", "PhongBan")
                        .WithMany("HopDong")
                        .HasForeignKey("PhongBanMaPB")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("Luong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.HopDong", "HopDong")
                        .WithMany("NhanVien")
                        .HasForeignKey("HopDongMaHD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.Luong", "Luong")
                        .WithMany("NhanVien")
                        .HasForeignKey("LuongHeSoLuong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyNhanSu.Data.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("PhongBanMaPB")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Luong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhuCap", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("PhuCap")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Taikhoan", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("Taikhoan")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ThuongPhat", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ThuongPhat")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ctChucVu", b =>
                {
                    b.HasOne("QuanLyNhanSu.Data.ChucVu", "ChucVu")
                        .WithMany("ctChucVu")
                        .HasForeignKey("ChucVuMaCV")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyNhanSu.Data.NhanVien", "NhanVien")
                        .WithMany("ctChucVu")
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.ChucVu", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.HopDong", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.Luong", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.NhanVien", b =>
                {
                    b.Navigation("BaoHiem");

                    b.Navigation("ChamCong");

                    b.Navigation("PhuCap");

                    b.Navigation("Taikhoan");

                    b.Navigation("ThuongPhat");

                    b.Navigation("ctChucVu");
                });

            modelBuilder.Entity("QuanLyNhanSu.Data.PhongBan", b =>
                {
                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
